/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*
* Model by Astronaut by Quaternius 
*/

import React, { useRef } from "react";
import { useGLTF, useAnimations } from "@react-three/drei";

export function Astro(props) {
  const group = useRef();
  const { nodes, materials, animations } = useGLTF("/astronaut.glb");
  const { actions } = useAnimations(animations, group);
  return (
    <group ref={group} {...props} dispose={null}>
      <group name="Root_Scene">
        <group name="RootNode" scale={0.2}>
          <group
            name="CharacterArmature"
            rotation={[-Math.PI / 2, 0, 0]}
            scale={100}
          >
            <primitive object={nodes.Root} />
          </group>
          <skinnedMesh
            name="BarbaraTheBee"
            geometry={nodes.BarbaraTheBee.geometry}
            material={materials.Atlas}
            skeleton={nodes.BarbaraTheBee.skeleton}
            rotation={[-Math.PI / 2, 0, 0]}
            scale={100}
          />
        </group>
      </group>
    </group>
  );
}

export default Astro;

useGLTF.preload("./astronaut.glb");