/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { forwardRef, useEffect } from "react";
import { useGLTF, useAnimations } from "@react-three/drei";

export function Sage(props) {
  const { nodes, materials, animations } = useGLTF("./sage.gltf");

  return (
    <group {...props} dispose={null}>
      <group name="Scene">
        <group name="Sage" position={[0.0, 0.0, 0.0]} scale={0.2}>
          <skinnedMesh
            name="Vieux"
            geometry={nodes.Vieux.geometry}
            material={materials["color_main.001"]}
            skeleton={nodes.Vieux.skeleton}
          />
          <primitive object={nodes.root} />
        </group>
      </group>
    </group>
  );
}

export default Sage;

useGLTF.preload("./sage.gltf");


